#!/usr/bin/env python3

import gevent
from gevent import monkey, socket
monkey.patch_all()
import requests
import sys
from dnslib import DNSRecord

#import logging
#logging.basicConfig(level=logging.DEBUG)

sess = requests.Session()
sess.mount('https://',
           requests.adapters.HTTPAdapter(pool_connections=50,
                                         pool_maxsize=75,
                                         max_retries=3))

def query(url, data, sock):
        try:
            print('send query', DNSRecord.parse(data).q.qname, "to", url)
            headers = {'accept': 'application/dns-message',
                       'content-type': 'application/dns-message'}
            r = sess.post(url, headers = headers, data = data)
            sock.send(r.content)
            while True:
                _ = sock.recv(1500)
                sock.send(r.content)
        except:
            pass

def forward_query(port, url):
    while True:
        sock = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM, 0)
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock.bind(('', port))
        data, addr = sock.recvfrom(1500)
        sock.connect(addr)
        sock.settimeout(6) # for 3 times retry
        gevent.spawn(query, url, data, sock)

if __name__ == "__main__":
    if len(sys.argv) == 3 and sys.argv[1] == '-f':
        exec(open(sys.argv[2]).read())
    else:
        exec(open("/etc/forwardoh.conf").read())
    forward_query(port, url)
