#!/usr/bin/env python3

import socket
import requests
import sys

def forward_query(port, url):
    sock = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM, 0)
    sock.bind(('', port))

    data, addr = sock.recvfrom(1500)
    headers = {'accept': 'application/dns-message',
               'content-type': 'application/dns-message'}
    r = requests.post(url, headers = headers, data = data)
    sock.sendto(r.content, addr)

if __name__ == "__main__":
    port = int(sys.argv[1])
    url = sys.argv[2]
    forward_query(port, url)
